query Category($filter: CategoryPublicFilter) {
  category(filter: $filter) {
    _id
    name
    description
    icon
    facilities {
      count
      items {
        _id
        name
        cover
        reviews {
          _id
          rating
        }
      }
    }
  }
}
