query Profile {
	profile {
		_id
		firstname
		lastname
		email
		phone
		role
		facilities {
			_id
			name
		}
    reservations {
      _id
      code
      barcode_url
      facility {
        _id
        name
        location {
          address
          city
          state
          country {
            _id
            name
          }
        }
      }
      seats
      date_reserved
      time_reserved
      current_status
    }
	}
}
