query Reservations ($filter: FilterFindManyReservationInput) {
  reservations (filter: $filter) {
    count
    items {
      _id
      facility {
        _id
        name
        location {
          address
          city
          state
          country {
            _id
            name
          }
        }
      }
      seats
      date_reserved
      statuses {
        _id
        status
      }
    }
  }
}